#Angel Collazo

#September 25, 2025

#P1HW1

#Collect information of the user, process information collected and display resuts to the user



#Calculating Exponents

print("Calculating Exponents")
base_num= int(input("Enter an integer as base value: "))
exponent_num= int(input("Enter an integer as the exponent: "))
power_result= base_num ** exponent_num
print("\n",base_num,"raise to the power of", exponent_num, "is", power_result, "!!")



#Addition and Subtraction

print("Addition and Subtraction")
start_value= int(input("Enter the starting integer: "))
add_value= int(input("Enter the integer to add: "))
subtract_value= int(input("Enter the integer to subtract: "))
total_result= start_value + add_value - subtract_value
print("\n",start_value,"+", add_value,"-", subtract_value,"equals to", total_result) 






